CREATE TABLE route_definitions (id varchar(36) PRIMARY KEY,protocol varchar(16) NOT NULL,method varchar(16) NOT NULL,path varchar(512) NOT NULL,operation text NOT NULL,description text NOT NULL,service_name varchar(128) NOT NULL,source_version varchar(128) NOT NULL,status varchar(16) NOT NULL,last_discovered_at timestamp(6) NOT NULL,created_at timestamp(6) NOT NULL,created_by text NOT NULL,updated_at timestamp(6) NOT NULL,updated_by text NOT NULL,version bigint NOT NULL,deleted_at timestamp(6) NULL,deleted_by text NULL,UNIQUE KEY route_definitions_identity_unique(service_name,protocol,method,path),INDEX route_definitions_status_idx(service_name,status,protocol));
CREATE TABLE route_policy_definitions (id varchar(36) PRIMARY KEY,route_id varchar(36) NOT NULL,expression text NOT NULL,description text NOT NULL,status varchar(16) NOT NULL,created_at timestamp(6) NOT NULL,created_by text NOT NULL,updated_at timestamp(6) NOT NULL,updated_by text NOT NULL,version bigint NOT NULL,deleted_at timestamp(6) NULL,deleted_by text NULL,UNIQUE KEY route_policy_definitions_route_unique(route_id));
CREATE TABLE route_policy_permission_refs (id varchar(36) PRIMARY KEY,policy_id varchar(36) NOT NULL,permission_key varchar(128) NOT NULL,resource varchar(128) NOT NULL,action varchar(128) NOT NULL,scope varchar(16) NOT NULL,created_at timestamp(6) NOT NULL,created_by text NOT NULL,updated_at timestamp(6) NOT NULL,updated_by text NOT NULL,version bigint NOT NULL,deleted_at timestamp(6) NULL,deleted_by text NULL,UNIQUE KEY route_policy_permission_refs_key_unique(policy_id,permission_key),INDEX route_policy_permission_refs_policy_idx(policy_id));
CREATE TRIGGER route_definitions_audit_bi BEFORE INSERT ON route_definitions FOR EACH ROW SET NEW.created_at=CURRENT_TIMESTAMP(6),NEW.created_by=NULLIF(TRIM(@app_actor_id),''),NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=1,NEW.deleted_at=NULL,NEW.deleted_by=NULL;
CREATE TRIGGER route_definitions_audit_bu BEFORE UPDATE ON route_definitions FOR EACH ROW SET NEW.created_at=OLD.created_at,NEW.created_by=OLD.created_by,NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=OLD.version+1,NEW.deleted_by=CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id),'') ELSE OLD.deleted_by END;
CREATE TRIGGER route_definitions_audit_bd BEFORE DELETE ON route_definitions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='physical delete is forbidden';
CREATE TRIGGER route_policy_definitions_audit_bi BEFORE INSERT ON route_policy_definitions FOR EACH ROW SET NEW.created_at=CURRENT_TIMESTAMP(6),NEW.created_by=NULLIF(TRIM(@app_actor_id),''),NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=1,NEW.deleted_at=NULL,NEW.deleted_by=NULL;
CREATE TRIGGER route_policy_definitions_audit_bu BEFORE UPDATE ON route_policy_definitions FOR EACH ROW SET NEW.created_at=OLD.created_at,NEW.created_by=OLD.created_by,NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=OLD.version+1,NEW.deleted_by=CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id),'') ELSE OLD.deleted_by END;
CREATE TRIGGER route_policy_definitions_audit_bd BEFORE DELETE ON route_policy_definitions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='physical delete is forbidden';
CREATE TRIGGER route_policy_permission_refs_audit_bi BEFORE INSERT ON route_policy_permission_refs FOR EACH ROW SET NEW.created_at=CURRENT_TIMESTAMP(6),NEW.created_by=NULLIF(TRIM(@app_actor_id),''),NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=1,NEW.deleted_at=NULL,NEW.deleted_by=NULL;
CREATE TRIGGER route_policy_permission_refs_audit_bu BEFORE UPDATE ON route_policy_permission_refs FOR EACH ROW SET NEW.created_at=OLD.created_at,NEW.created_by=OLD.created_by,NEW.updated_at=CURRENT_TIMESTAMP(6),NEW.updated_by=NULLIF(TRIM(@app_actor_id),''),NEW.version=OLD.version+1,NEW.deleted_by=CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id),'') ELSE OLD.deleted_by END;
CREATE TRIGGER route_policy_permission_refs_audit_bd BEFORE DELETE ON route_policy_permission_refs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='physical delete is forbidden';
SET @app_actor_id='application-service:migration';
INSERT INTO route_definitions(id,protocol,method,path,operation,description,service_name,source_version,status,last_discovered_at,created_at,created_by,updated_at,updated_by,version) VALUES
('68c5fcb6-2d64-57b7-b393-a753da4b712a','http','post','/api/v1/version','bootstrap.version','','application-service','migration-000007','active',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('8e4038d9-155e-5320-8e9b-30dcbe5de3b4','http','post','/api/v1/me','bootstrap.me','','application-service','migration-000007','active',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('05ddeb9e-0ba6-53d6-a4a6-58ee83005188','http','post','/api/v1/route-policies/page','bootstrap.route-policy.page','','application-service','migration-000007','active',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('fd87b9a5-18ea-5d7e-8d30-c6c62d9d8eda','http','post','/api/v1/route-policies/get','bootstrap.route-policy.get','','application-service','migration-000007','active',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('986d037e-007e-57d7-910e-64932ff0269a','http','post','/api/v1/route-policies/set','bootstrap.route-policy.set','','application-service','migration-000007','active',CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1);
INSERT INTO route_policy_definitions(id,route_id,expression,description,status,created_at,created_by,updated_at,updated_by,version) VALUES
('647996ac-0a7e-4d32-8a9d-c617b1721513','68c5fcb6-2d64-57b7-b393-a753da4b712a','anonymous || authenticated','Public version metadata','active',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('283e3549-89b9-4420-9b0a-a0c237045c59','8e4038d9-155e-5320-8e9b-30dcbe5de3b4','authenticated','Authenticated principal metadata','active',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('6f58b006-7a3f-443a-8dd2-66f890cae97e','05ddeb9e-0ba6-53d6-a4a6-58ee83005188','authenticated && permissions["application.catalog.update"]','Route policy administration','active',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('8410fa06-90c6-42cb-91a2-00667f23366b','fd87b9a5-18ea-5d7e-8d30-c6c62d9d8eda','authenticated && permissions["application.catalog.update"]','Route policy administration','active',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('f9054584-ecb4-4fdb-8faa-38c407de03c1','986d037e-007e-57d7-910e-64932ff0269a','authenticated && permissions["application.catalog.update"]','Route policy administration','active',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1);
INSERT INTO route_policy_permission_refs(id,policy_id,permission_key,resource,action,scope,created_at,created_by,updated_at,updated_by,version) VALUES
('d7d16540-87e0-4321-8bc9-9e6a1259122d','6f58b006-7a3f-443a-8dd2-66f890cae97e','application.catalog.update','application.catalog','update','platform',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('e8e81bb1-346a-4e74-937c-62a8984562fd','8410fa06-90c6-42cb-91a2-00667f23366b','application.catalog.update','application.catalog','update','platform',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1),
('5bd7c51e-18a2-4579-9ee3-5145a2f3270d','f9054584-ecb4-4fdb-8faa-38c407de03c1','application.catalog.update','application.catalog','update','platform',CURRENT_TIMESTAMP(6),'application-service:migration',CURRENT_TIMESTAMP(6),'application-service:migration',1);
