DROP INDEX application_menu_drafts_active_tree_idx ON application_menu_drafts;
DROP TRIGGER IF EXISTS application_outbox_events_audit_bu;
DROP TRIGGER IF EXISTS application_outbox_events_audit_bi;
ALTER TABLE application_outbox_events MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
DROP TRIGGER IF EXISTS tenant_application_grants_audit_bd;
DROP TRIGGER IF EXISTS tenant_application_grants_audit_bu;
DROP TRIGGER IF EXISTS tenant_application_grants_audit_bi;
ALTER TABLE tenant_application_grants MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
DROP TRIGGER IF EXISTS application_menu_release_items_audit_bd;
DROP TRIGGER IF EXISTS application_menu_release_items_audit_bu;
DROP TRIGGER IF EXISTS application_menu_release_items_audit_bi;
ALTER TABLE application_menu_release_items MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
DROP TRIGGER IF EXISTS application_menu_releases_audit_bd;
DROP TRIGGER IF EXISTS application_menu_releases_audit_bu;
DROP TRIGGER IF EXISTS application_menu_releases_audit_bi;
ALTER TABLE application_menu_releases MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
DROP TRIGGER IF EXISTS application_menu_drafts_audit_bd;
DROP TRIGGER IF EXISTS application_menu_drafts_audit_bu;
DROP TRIGGER IF EXISTS application_menu_drafts_audit_bi;
ALTER TABLE application_menu_drafts MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
DROP TRIGGER IF EXISTS applications_audit_bd;
DROP TRIGGER IF EXISTS applications_audit_bu;
DROP TRIGGER IF EXISTS applications_audit_bi;
ALTER TABLE applications MODIFY COLUMN created_at DATETIME(6) NOT NULL, MODIFY COLUMN updated_at DATETIME(6) NOT NULL, DROP COLUMN deleted_by,DROP COLUMN deleted_at;
