CREATE TABLE route_definitions (id text PRIMARY KEY,protocol text NOT NULL,method text NOT NULL,path text NOT NULL,operation text NOT NULL DEFAULT '',description text NOT NULL DEFAULT '',service_name text NOT NULL,source_version text NOT NULL,status text NOT NULL CHECK(status IN('active','inactive')),last_discovered_at timestamptz NOT NULL,created_at timestamptz NOT NULL,created_by text NOT NULL,updated_at timestamptz NOT NULL,updated_by text NOT NULL,version bigint NOT NULL CHECK(version>0),deleted_at timestamptz,deleted_by text);
CREATE UNIQUE INDEX route_definitions_identity_unique ON route_definitions(service_name,protocol,method,path) WHERE deleted_at IS NULL;
CREATE INDEX route_definitions_status_idx ON route_definitions(service_name,status,protocol) WHERE deleted_at IS NULL;
CREATE TRIGGER route_definitions_audit_row BEFORE INSERT OR UPDATE OR DELETE ON route_definitions FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TABLE route_policy_definitions (id text PRIMARY KEY,route_id text NOT NULL REFERENCES route_definitions(id),expression text NOT NULL,description text NOT NULL DEFAULT '',status text NOT NULL CHECK(status IN('active','disabled')),created_at timestamptz NOT NULL,created_by text NOT NULL,updated_at timestamptz NOT NULL,updated_by text NOT NULL,version bigint NOT NULL CHECK(version>0),deleted_at timestamptz,deleted_by text);
CREATE UNIQUE INDEX route_policy_definitions_route_unique ON route_policy_definitions(route_id) WHERE deleted_at IS NULL;
CREATE TRIGGER route_policy_definitions_audit_row BEFORE INSERT OR UPDATE OR DELETE ON route_policy_definitions FOR EACH ROW EXECUTE FUNCTION app_audit_row();
CREATE TABLE route_policy_permission_refs (id text PRIMARY KEY,policy_id text NOT NULL REFERENCES route_policy_definitions(id),permission_key text NOT NULL,resource text NOT NULL,action text NOT NULL,scope text NOT NULL CHECK(scope IN('tenant','platform','principal')),created_at timestamptz NOT NULL,created_by text NOT NULL,updated_at timestamptz NOT NULL,updated_by text NOT NULL,version bigint NOT NULL CHECK(version>0),deleted_at timestamptz,deleted_by text);
CREATE UNIQUE INDEX route_policy_permission_refs_key_unique ON route_policy_permission_refs(policy_id,permission_key) WHERE deleted_at IS NULL;
CREATE INDEX route_policy_permission_refs_policy_idx ON route_policy_permission_refs(policy_id) WHERE deleted_at IS NULL;
CREATE TRIGGER route_policy_permission_refs_audit_row BEFORE INSERT OR UPDATE OR DELETE ON route_policy_permission_refs FOR EACH ROW EXECUTE FUNCTION app_audit_row();
SELECT set_config('app.actor_id','application-service:migration',false);
INSERT INTO route_definitions(id,protocol,method,path,operation,description,service_name,source_version,status,last_discovered_at,created_at,created_by,updated_at,updated_by,version) VALUES
('68c5fcb6-2d64-57b7-b393-a753da4b712a','http','post','/api/v1/version','bootstrap.version','','application-service','migration-000007','active',statement_timestamp(),statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('8e4038d9-155e-5320-8e9b-30dcbe5de3b4','http','post','/api/v1/me','bootstrap.me','','application-service','migration-000007','active',statement_timestamp(),statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('05ddeb9e-0ba6-53d6-a4a6-58ee83005188','http','post','/api/v1/route-policies/page','bootstrap.route-policy.page','','application-service','migration-000007','active',statement_timestamp(),statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('fd87b9a5-18ea-5d7e-8d30-c6c62d9d8eda','http','post','/api/v1/route-policies/get','bootstrap.route-policy.get','','application-service','migration-000007','active',statement_timestamp(),statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('986d037e-007e-57d7-910e-64932ff0269a','http','post','/api/v1/route-policies/set','bootstrap.route-policy.set','','application-service','migration-000007','active',statement_timestamp(),statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1);
INSERT INTO route_policy_definitions(id,route_id,expression,description,status,created_at,created_by,updated_at,updated_by,version) VALUES
('647996ac-0a7e-4d32-8a9d-c617b1721513','68c5fcb6-2d64-57b7-b393-a753da4b712a','anonymous || authenticated','Public version metadata','active',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('283e3549-89b9-4420-9b0a-a0c237045c59','8e4038d9-155e-5320-8e9b-30dcbe5de3b4','authenticated','Authenticated principal metadata','active',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('6f58b006-7a3f-443a-8dd2-66f890cae97e','05ddeb9e-0ba6-53d6-a4a6-58ee83005188','authenticated && permissions["application.catalog.update"]','Route policy administration','active',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('8410fa06-90c6-42cb-91a2-00667f23366b','fd87b9a5-18ea-5d7e-8d30-c6c62d9d8eda','authenticated && permissions["application.catalog.update"]','Route policy administration','active',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('f9054584-ecb4-4fdb-8faa-38c407de03c1','986d037e-007e-57d7-910e-64932ff0269a','authenticated && permissions["application.catalog.update"]','Route policy administration','active',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1);
INSERT INTO route_policy_permission_refs(id,policy_id,permission_key,resource,action,scope,created_at,created_by,updated_at,updated_by,version) VALUES
('d7d16540-87e0-4321-8bc9-9e6a1259122d','6f58b006-7a3f-443a-8dd2-66f890cae97e','application.catalog.update','application.catalog','update','platform',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('e8e81bb1-346a-4e74-937c-62a8984562fd','8410fa06-90c6-42cb-91a2-00667f23366b','application.catalog.update','application.catalog','update','platform',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1),
('5bd7c51e-18a2-4579-9ee3-5145a2f3270d','f9054584-ecb4-4fdb-8faa-38c407de03c1','application.catalog.update','application.catalog','update','platform',statement_timestamp(),'application-service:migration',statement_timestamp(),'application-service:migration',1);
